default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project domenico-falco
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_CREDS

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/domenico-falco/domenico-falco

deploy:
  stage: deploy
  script:
    - gcloud run deploy domenico-falco --image gcr.io/domenico-falco/domenico-falco --platform managed --region europe-west4 --allow-unauthenticated
  only:
    - main
