default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project PROJECT-ID

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/PROJECT-ID/cicd2

deploy:
  stage: deploy
  script:
    - gcloud run deploy cicd2 --image gcr.io/PROJECT-ID/cicd2 --platform managed --region us-west1 --allow-unauthenticated
