# Node docker image on which this would be run
image: node:12

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy_production

# Job 1:
Build:
  stage: build
  script:
    - npm install
    - npm run build

# Job 2:
Production:
  image: ruby:latest
  only:
    - main
  stage: deploy_production
  script:
    - npm run deploy
