default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project dfalco-com
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_CREDS

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/dfalco-com/cicd

deploy:
  stage: deploy
  script:
    - gcloud run deploy cicd --image gcr.io/dfalco-com/cicd --platform managed --region us-west1 --allow-unauthenticated
