default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud config set project dfalco-com
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_CREDS

build:
  stage: build
  script:
    - gcloud builds submit --tag gcr.io/dfalco-com/dfalco-com

deploy:
  stage: deploy
  script:
    - gcloud run deploy dfalco-com --image gcr.io/dfalco-com/dfalco-com --platform managed --region europe-west4 --allow-unauthenticated
